import type { Metadata } from "next";
import localFont from "next/font/local";
import cn from "classnames";

import Header from "@/components/layouts/header/Header";

import "../styles/globals.scss";
import styles from "./layout.module.scss";

const ntsomic = localFont({
  variable: "--font-ntsomic",
  src: [
    { path: "../../public/fonts/NTSomic-Regular.woff2", weight: "400" },
    { path: "../../public/fonts/NTSomic-Regular.woff", weight: "400" },
    { path: "../../public/fonts/NTSomic-Medium.woff2", weight: "500" },
    { path: "../../public/fonts/NTSomic-Medium.woff", weight: "500" },
    { path: "../../public/fonts/NTSomic-Semibold.woff2", weight: "600" },
    { path: "../../public/fonts/NTSomic-Semibold.woff", weight: "600" },
    { path: "../../public/fonts/NTSomic-Bold.woff2", weight: "700" },
    { path: "../../public/fonts/NTSomic-Bold.woff", weight: "700" },
  ],
});

const patsySans = localFont({
  variable: "--font-patsysans",
  src: [
    { path: "../../public/fonts/PatsySansRegular.woff2", weight: "400" },
    { path: "../../public/fonts/PatsySansRegular.woff", weight: "400" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`${ntsomic.variable} ${patsySans.variable}`, styles.container)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
